name = "Custom Theme"
license = "MIT"
licenselink = "LICENSE"
description = "A minimal starting point for a Micro.blog theme."
homepage = "https://github.com/yourusername/yourtheme"
tags = ["blog", "microblog"]
features = []
min_version = "0.91"

[author]
  name = "Juha Liikala"
  homepage = "https://juhaliikala.com"
